export { default as serviceController } from './service.controller';
export { default as slotGeneratorController } from './slotGenerator.controller';
export { default as consultantAvailabilityController } from './consultantAvailability.controller';
export { default as consultantExceptionController } from './consultantException.controller';
export { default as appointmentController } from './appointment.controller';
export { default as availableSlotController } from './availableSlot.controller';
export { default as appointmentStatusController } from './appointmentStatus.controller';
export { default as consultantNotificationController } from './consultantNotification.controller';
export { default as notificationTypeController } from './notificationType.controller';